### ISSUE TITLE
Error: [msgfmt] Installed but msgfmt.init('en') etc was never called

### ISSUE THREAD

**Issue by MHerszak** [tomitrescak/meteor-boilerplate-typescript#1]
Hello,

I am about to test your boilerplate and I got an error. Do you have an idea on how I can avoid it?

Error: [msgfmt] Installed but msgfmt.init('en') etc was never called.
    at packages/msgfmt:core/lib/mfPkg/messageformat-server.js:422:1
    at /Users/michelherszak/Projects/JavaScript/meteor-boilerplate-typescript/src/.meteor/local/build/programs/server/boot.js:229:5
Exited with code: 8
Your application is crashing. Waiting for file change.

**Comment by dasdeck** [comment]
Hey, I seem to have a related Issue:

https://github.com/gadicc/meteor-messageformat/issues/242

Do you have an idea?
